price: determine the price of an article on the internet. fix some issues pull

diff --git a/filter b/filter
--- a/filter
+++ b/filter
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-#set -x
-
 # cmd line options
 CSV_DIR=''
 IMG_DIR=''
@@ -57,16 +55,17 @@ parse_args_prepare() {
       exit 1
    }
 
-   ERROR=$(mkdir -p "$CLEAN_CSV_DIR" 2>&1)
-   if [ "$ERROR" ] ; then
-      printf '%s: ERROR: %s\n' "$0" "$ERROR" >&2
+   ERROR_MSG=$(mkdir -p "$CLEAN_CSV_DIR" 2>&1)
+   if [ "$ERROR_MGS" ] ; then
+      printf '%s: ERROR: %s\n' "$0" "$ERROR_MSG" >&2
       exit 1
    fi
 
-   STAT="$CLEAN_CSV_DIR"/stat
-   touch "$STAT"
    test -w "$IMG_DIR" && CAN_DEL_IMAGE=CAN_DEL_IMAGE
    test -w "$CSV_DIR" && CAN_MOD_RECORD=CAN_MOD_RECORD
+
+   STAT="$CLEAN_CSV_DIR"/stat
+   touch "$STAT"
 }
 
 
diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -9,12 +9,12 @@ alias ima='python ~/ground/projects/ima/src/__main__.py'
 W_PIDS=''
 
 # ima options
-ENGINE='duckduckgo'
+ENGINE='google,duckduckgo'
 N_IMAGES=20
 N_IMAGES_SITES=5
 N_SITES=10
-TIMEOUT=20
-N_RETRYS=1000000
+TIMEOUT=30
+N_RETRYS=100000000000
 N_RETRYS_SITES=5
 
 # vars for cmd options
@@ -26,13 +26,14 @@ trap spawn_workers ALRM
 trap kill_workers KILL TERM HUP STOP INT
 
 usage () {
-   printf 'Usage: %s [-h] [-i IMAGE_DIR] [-c CSV_DIR] [-w N]\n' "$0" >&2
-   printf '\t-h: Display this help message an exit\n' >&2
-   printf '\t-w: Specify the number of worker processes\n' >&2
-   printf '\t-i: Specify the path to where images will be stored\n' >&2
-   printf '\t-c: Specify the path to where CSV files will be store\n' >&2
+   printf 'Usage: %s [-h] [-i IMAGE_DIR] [-c CSV_DIR] [-w N] [-s SCORE]\n' "$0" >&2
+   printf '\t-h: Display this help message an exit.\n' >&2
+   printf '\t-w: The number of worker processes.\n' >&2
+   printf '\t-i: The path to where images will be stored.\n' >&2
+   printf '\t-c: The path to where CSV files will be stored.\n' >&2
+   printf '\t-s: Define minimum score for images.\n' >&2
    printf '\n' >&2
-   printf 'NOTE: All arguments are mandatory in the exception of -h\n' >&2
+   printf 'NOTE: All options with arguments are mandatory.\n' >&2
    exit 1
 }
 
@@ -49,6 +50,13 @@ check_requirements () {
       fi
    done
 
+   is_digit() {
+      expr "$2" : '+\?[0-9]\+$' >/dev/null || {
+         printf "%s: ERROR: argument to '%s' must be a positive integer\n" "$0" "$1">&2
+         exit 1
+      }
+   }
+
    test $# -eq 0 && usage
    while test $# -gt 0 ; do
       expr "$1" : '-h$' >/dev/null && usage
@@ -57,11 +65,12 @@ check_requirements () {
       expr "$2" : '-' >/dev/null && usage
       case "$1" in
          -w)
-            expr "$2" : '+\?[0-9]\+$' >/dev/null || {
-               printf "%s: ERROR: argument to -w must be a positive integer\n" "$0" >&2
-               exit 1
-            }
+            is_digit -w "$2"
             N_WORKERS=$2
+            ;;
+         -s)
+            is_digit -s "$2"
+            IMAGE_SCORE=$2
             ;;
          -c)
             CSV_DIR=$2
@@ -79,7 +88,7 @@ check_requirements () {
 
    if test -z "$CSV_DIR" || test -z "$IMAGE_DIR" || test -z "$N_WORKERS"
    then
-      printf '%s: ERROR: all arguments are mandatory\n' "$0" >&2
+      printf '%s: ERROR: all options are mandatory\n' "$0" >&2
       usage
    fi
 
@@ -148,8 +157,6 @@ spawn_workers () {
             s/[-_ \t;.]*$//'
             #y///g'
       )_$(mktemp -u XXXXXX).csv"
-      echo $CSV_FILE
-      exit 1
 
       ima -n $N_IMAGES \
          --image-count $N_IMAGES_SITES \
@@ -159,11 +166,11 @@ spawn_workers () {
          --retrys $N_RETRYS \
          --retrys-per-sites $N_RETRYS_SITES \
          --image-link '{w} {l} {e}' "$QUERY" |
-      while read FOUND ; do
-         SITE=$(printf '%s\n' "$FOUND" | awk -F[' '] '{print $1}')
-         LINK=$(printf '%s\n' "$FOUND" | awk -F[' '] '{print $2}')
-         IMG_FILE=$(mktemp -u XXXXXX).$(printf '%s\n' "$FOUND" | awk -F[' '] '{print $3}')
-         ABS_PATH_FILE="${IMAGE_DIR%%/}/$FILENAME"
+      while read RECORD ; do
+         SITE=$(printf '%s\n' "$RECORD" | awk -F[' '] '{print $1}')
+         LINK=$(printf '%s\n' "$RECORD" | awk -F[' '] '{print $2}')
+         IMG_FILE="$(mktemp -u XXXXXX).$(printf '%s\n' "$RECORD" | awk -F[' '] '{print $3}')"
+         ABS_PATH_FILE="${IMAGE_DIR%%/}/$IMG_FILE"
 
          wget --quiet --tries 10 "$LINK" --output-document="$ABS_PATH_FILE"
          if test $? -eq 0 ; then
